# Generated by Django 5.0.1 on 2024-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_created_at_show_description_show_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
